---
- name: Check if the current version is installed.
  stat:
    path: "{{ promtail_home_dir }}/promtail-{{ promtail_version }}"
  register: promtail_version_stats

- name: Download promtail.
  when: promtail_version_stats.stat.exists == false
  get_url:
    url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
    dest: "{{ promtail_home_dir }}/promtail-linux-amd64.zip"
    force: yes

- name: Unpack tarball.
  when: promtail_version_stats.stat.exists == false
  unarchive:
    src: "{{ promtail_home_dir }}/promtail-linux-amd64.zip"
    dest: "{{ promtail_home_dir }}"
    remote_src: yes

- name: Copy systemd service file.
  template: src=promtail.service.j2 dest=/etc/systemd/system/promtail.service
  notify:
    - restart promtail

- name: Create symlink.
  file:
    src: "{{ promtail_home_dir }}/promtail-{{ promtail_version }}"
    dest: "{{ promtail_executable }}"
    state: link
  notify:
    - restart promtail
